version: '3'

services:
  mysql:
        image: mysql:latest
        build: DBDOKER/
        restart: on-failure
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sakila
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        command: --performance-schema --secure-file-priv=""
        volumes:
        - ./testdata/schema/:/docker-entrypoint-initdb.d/:rw
        networks:
          testing_net:
            ipv4_address: 172.23.0.2
  speedment-app:
        image: openjdk:11
        build: .
        restart: on-failure
        ports:
        - '8878:8080'
        networks:
          testing_net:
            ipv4_address: 172.23.0.3
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
